name: Github Actions Kotlin Standard
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test-and-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Before Install
        run: |
          chmod +x gradlew
          chmod +x gradle/wrapper/gradle-wrapper.jar
      - name: Run Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CORRECT_COVERAGE: ${{ secrets.CORRECT_COVERAGE }}
        run: |
          ./gradlew build
          ./gradlew test
          bash <(curl -s https://codecov.io/bash)
          ./gradlew run
      - name: Upstream to Standards
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: ${{ github.event_name == 'push'}}
        run: |
          ./upstream.sh
